baseURL = 'https://rhyannonjoy.github.io/agent-ecosystem-glossary/'
locale = 'en-us'
title = "Agent Ecosystem Glossary"

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"

[params]
  BookRepo = 'https://github.com/rhyannonjoy/agent-ecosystem-glossary'
  BookEditPath = 'edit/main'
  BookToC = true  # This enables the right sidebar TOC
  BookSection = '*'
  BookSearch = false