# test locally
# rm -rf resources/
# rm -rf public/
# hugo server -D

baseURL = 'https://rhyannonjoy.github.io/agent-ecosystem-glossary/'
languageCode = 'en-us'
title = "Agent Ecosystem Glossary"

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"

[params]
  BookRepo = 'https://github.com/rhyannonjoy/agent-ecosystem-glossary'
  BookEditPath = 'edit/main'
  BookSearch = true
  BookToC = true  # This enables the right sidebar TOC
  BookSection = '*'